---
version: '2'
services:
  redis:
    image: redis/redis:latest
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    # No username/password is given, so authentication is disabled
    #environment:
    volumes:
     - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo:mongo
    ports:
      - 127.0.0.1:8081:8081
    env_file:
      - secrets.env

  ttn-redis-producer:
    build: ttn-redis-producer
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_SERVER: redis:6379
    env_file:
     - secrets.env
     - ttn-redis-producer/config.env

  ttn-redis-decoder:
    build: ttn-redis-decoder
    restart: always
    links:
      - redis:redis
      - mongo:mongo
      - elasticsearch:elasticsearch
    environment:
      REDIS_SERVER: redis:6379
      MONGODB_URL: mongodb://mongo:27017
      ELASTIC_HOST: elasticsearch
    env_file:
     - ttn-redis-decoder/config.env

  ttn-redis-converter:
    build: ttn-redis-converter
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_SERVER: redis:6379
    env_file:
     - secrets.env
     - ttn-redis-converter/config.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    restart: always
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      discovery.type: single-node
      # Disable disk space monitoring (which is pointless with a single
      # node and only ends up making things readonly when a disk is
      # "almost" full, which is 90% full by default).
      cluster.routing.allocation.disk.threshold_enabled: "false"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - 127.0.0.1:5601:5601

  grafana:
    image: grafana/grafana
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - 127.0.0.1:3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  mongo-data:
  redis-data:
