---
version: '2'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/data

  timescale:
    image: timescale/timescaledb:latest-pg11
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - timescale-data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.9
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - timescale
    restart: always
    links:
      - timescale:timescale
    env_file:
      - secrets.env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@timescale:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

  ttn-redis-producer:
    build: ttn-redis-producer
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
     - secrets.env
     - ttn-redis-producer/config.env

  ttn-redis-decoder:
    build: ttn-redis-decoder
    restart: always
    links:
      - redis:redis
      - elasticsearch:elasticsearch
      - timescale:timescale
    environment:
      REDIS_URL: redis://redis:6379/0
      ELASTIC_HOST: elasticsearch
      DATABASE_URL: postgres://postgres:password@timescale:5432/postgres
    env_file:
     - ttn-redis-decoder/config.env

  ttn-redis-converter:
    build: ttn-redis-converter
    restart: always
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
     - secrets.env
     - ttn-redis-converter/config.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    restart: always
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      discovery.type: single-node
      # Disable disk space monitoring (which is pointless with a single
      # node and only ends up making things readonly when a disk is
      # "almost" full, which is 90% full by default).
      cluster.routing.allocation.disk.threshold_enabled: "false"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - 127.0.0.1:5601:5601

  grafana:
    image: grafana/grafana
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - 127.0.0.1:3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  redis-data:
  timescale-data:
